import os
import json
import time

from typing import Optional

from fastapi import FastAPI, HTTPException, Depends, Query, Request, Header
from pydantic import BaseModel

from sqlalchemy.orm import Session
from sqlalchemy.exc import IntegrityError
from dotenv import load_dotenv

from schemas.passport import (
    MerchantPassport,
    ProductListing,
    NegotiationPolicy
)

from schemas.mandate import BuyerIntentMandate

from schemas.transaction import (
    TransactionResponse,
    AuditLedgerResponse
)

from core.database import (
    get_db,
    ProductInventory,
    StockReservationQuote,
    AuditEventLog,
    TransactionLedger
)

from core.audit_service import AuditService
from core.policy_engine import DeterministicPolicyEngine
from core.razorpay_gateway import RazorpayPaymentService

from agents.merchant_agent import MerchantSalesAgent
from agents.buyer_agent import AutonomousBuyerAgent


# ---------------------------------------------------------
# ENVIRONMENT
# ---------------------------------------------------------

load_dotenv()


# ---------------------------------------------------------
# APPLICATION
# ---------------------------------------------------------

app = FastAPI(
    title="AgentReady Autonomous Commerce Gateway",
    description=(
        "Policy-governed Agent-to-Agent Commerce Gateway. "
        "LLMs and agents may propose and negotiate, but the "
        "deterministic Payment Trust Engine controls payment actions."
    ),
    version="1.0.0"
)


# ---------------------------------------------------------
# NATURAL LANGUAGE INTENT REQUEST
# ---------------------------------------------------------

class NaturalLanguageIntentRequest(BaseModel):
    """
    Unstructured buyer request submitted to the AI intent parser.
    """

    prompt: str


# ---------------------------------------------------------
# SERVICES
# ---------------------------------------------------------

merchant_agent = MerchantSalesAgent()
payment_service = RazorpayPaymentService()


# ---------------------------------------------------------
# HELPER FUNCTIONS
# ---------------------------------------------------------

def is_mock_order(order: dict) -> bool:
    """
    Determines whether the returned order was generated by
    the clearly labelled local MOCK/DEMO fallback.
    """

    order_id = str(order.get("id", ""))

    return (
        order_id.startswith("order_mock_")
        or order_id.startswith("order_sim_")
    )


def get_existing_transaction_for_request(
    db: Session,
    mandate_id: str,
    product_id: str
):
    """
    Replay protection before creating another quote reservation.

    This prevents a repeated request for the same mandate/product
    from creating another order after an earlier successful order
    already exists.

    The canonical idempotency key remains stored in the ledger.
    """

    return (
        db.query(TransactionLedger)
        .filter(
            TransactionLedger.mandate_id == mandate_id,
            TransactionLedger.product_id == product_id,
            TransactionLedger.status.in_(
                [
                    "ORDER_CREATED_TEST_MODE",
                    "ORDER_CREATED_MOCK_MODE"
                ]
            )
        )
        .order_by(TransactionLedger.created_at.asc())
        .first()
    )


def release_expired_quote_if_needed(
    db: Session,
    quote: StockReservationQuote
):
    """
    Releases inventory if the quote has expired before payment.
    """

    now = int(time.time())

    if (
        quote
        and quote.status == "RESERVED"
        and now > quote.expires_at
    ):
        MerchantSalesAgent.release_reservation(
            db,
            quote.quote_id,
            reason="EXPIRED"
        )

        return True

    return False


# ---------------------------------------------------------
# HEALTH / ROOT
# ---------------------------------------------------------

@app.get("/")
def root():
    return {
        "service": "AgentReady",
        "status": "RUNNING",
        "payment_control": (
            "DETERMINISTIC_PAYMENT_TRUST_ENGINE"
        ),
        "demo_mode": True
    }


# ---------------------------------------------------------
# MERCHANT AI PASSPORT
# ---------------------------------------------------------

@app.get(
    "/.well-known/ai-passport.json",
    response_model=MerchantPassport
)
def get_merchant_passport(
    db: Session = Depends(get_db)
):
    """
    Machine-readable Merchant AI Passport.

    This endpoint exposes merchant capabilities and live
    catalog/inventory information.

    IMPORTANT:
    is_demo_verified means demo verification only.
    It does NOT claim official Razorpay, NPCI, GSTIN,
    UAP, government, or banking verification.
    """

    items = (
        db.query(ProductInventory)
        .filter(
            ProductInventory.merchant_id
            == "mer_techgear_01"
        )
        .all()
    )

    catalog_listings = []

    for item in items:

        catalog_listings.append(
            ProductListing(
                product_id=item.product_id,
                name=item.name,
                category=item.category,
                retail_price_paise=item.retail_price_paise,
                cost_price_paise=item.cost_price_paise,
                stock_total=item.stock_total,
                stock_available=item.stock_available,
                stock_reserved=item.stock_reserved,
                stock_sold=item.stock_sold
            )
        )

    return MerchantPassport(
        merchant_id="mer_techgear_01",
        name="TechGear Store",
        trust_score=94.5,

        # Truthful demo-only verification indicator
        is_demo_verified=True,

        return_window_days=7,

        catalog=catalog_listings,

        negotiation_policy=merchant_agent.policy,

        payment_rails=[
            "RAZORPAY_TEST_MODE",
            "MOCK_GATEWAY"
        ]
    )


# ---------------------------------------------------------
# NATURAL LANGUAGE AI INTENT PARSER
# ---------------------------------------------------------

@app.post(
    "/api/v1/agent/parse-intent",
    response_model=BuyerIntentMandate
)
def parse_natural_language_intent(
    payload: NaturalLanguageIntentRequest
):
    """
    Converts an unstructured natural-language buyer request
    into a typed and bounded BuyerIntentMandate.

    The LLM may extract structured purchase intent only.

    The LLM does NOT control:
    - payment execution
    - Razorpay order creation
    - policy decisions
    - stock consumption

    All transaction authorization remains controlled by the
    deterministic Payment Trust Engine.
    """

    return AutonomousBuyerAgent.parse_intent_with_llm(
        payload.prompt
    )


# ---------------------------------------------------------
# MAIN AGENT TRANSACTION
# ---------------------------------------------------------

@app.post(
    "/api/v1/agent/transact",
    response_model=TransactionResponse
)
def execute_agent_transaction(

    mandate: BuyerIntentMandate,

    product_id: str = Query(
        ...,
        description="Target product identifier"
    ),

    bid_unit_price_paise: int = Query(
        ...,
        description=(
            "Buyer offered unit price "
            "in integer paise"
        )
    ),

    db: Session = Depends(get_db)

):
    """
    Main policy-governed transaction flow.

    FLOW:

    1. Receive typed buyer mandate
    2. Check replay / duplicate request
    3. Validate product exists
    4. Request merchant quote
    5. Reserve inventory
    6. Validate quote using deterministic policy engine
    7. Create Razorpay TEST MODE order or MOCK order
    8. Consume reserved stock only after order creation
    9. Persist ledger and audit trail

    The merchant/agent layer never directly bypasses
    the deterministic policy engine.
    """


    # -----------------------------------------------------
    # STEP 1
    # MANDATE INGESTION AUDIT
    # -----------------------------------------------------

    AuditService.log_event(
        db=db,

        mandate_id=mandate.mandate_id,

        event_type="MANDATE_INGESTION",

        actor="BUYER_AGENT",

        status="INFO",

        payload={
            "user_id": mandate.user_id,
            "category": mandate.category,
            "max_budget_paise": mandate.max_budget_paise,
            "target_quantity": mandate.target_quantity,
            "allowed_merchants": mandate.allowed_merchants,
            "created_at": mandate.created_at,
            "expiry_seconds": mandate.expiry_seconds
        }
    )


    # -----------------------------------------------------
    # STEP 2
    # MANDATE EXPIRY PRE-CHECK
    # -----------------------------------------------------

    current_time = int(time.time())

    mandate_expiry = (
        mandate.created_at
        + mandate.expiry_seconds
    )

    if current_time > mandate_expiry:

        reason_code = "MANDATE_EXPIRED"

        message = (
            "The delegated purchase mandate has expired. "
            "No order or payment action was performed."
        )

        AuditService.log_event(
            db=db,

            mandate_id=mandate.mandate_id,

            event_type="MANDATE_REJECTED",

            actor="POLICY_ENGINE",

            status="BLOCKED",

            payload={
                "decision": "BLOCK",
                "reason_code": reason_code,
                "message": message,
                "mandate_expiry": mandate_expiry,
                "current_time": current_time
            }
        )

        raise HTTPException(
            status_code=400,

            detail={
                "decision": "BLOCK",
                "reason_code": reason_code,
                "message": message
            }
        )


    # -----------------------------------------------------
    # STEP 3
    # PRODUCT LOOKUP
    # -----------------------------------------------------

    product_record = (
        db.query(ProductInventory)
        .filter(
            ProductInventory.product_id
            == product_id
        )
        .first()
    )

    if not product_record:

        AuditService.log_event(
            db=db,

            mandate_id=mandate.mandate_id,

            event_type="CATALOG_LOOKUP_FAILED",

            actor="BUYER_AGENT",

            status="FAILED",

            payload={
                "product_id": product_id,
                "reason": "PRODUCT_NOT_FOUND"
            }
        )

        raise HTTPException(
            status_code=404,

            detail={
                "decision": "BLOCK",
                "reason_code": "PRODUCT_NOT_FOUND",
                "message": (
                    "Requested product does not exist "
                    "in merchant inventory."
                )
            }
        )


    # -----------------------------------------------------
    # STEP 4
    # REPLAY / DUPLICATE PROTECTION
    #
    # IMPORTANT:
    # Check BEFORE creating another stock reservation.
    # -----------------------------------------------------

    existing_tx = get_existing_transaction_for_request(
        db=db,

        mandate_id=mandate.mandate_id,

        product_id=product_id
    )

    if existing_tx:

        retail_total_paise = (
            product_record.retail_price_paise
            * existing_tx.quantity
        )

        savings_paise = max(
            0,

            retail_total_paise
            - existing_tx.total_amount_paise
        )

        AuditService.log_event(
            db=db,

            mandate_id=mandate.mandate_id,

            event_type="IDEMPOTENCY_HIT",

            actor="POLICY_ENGINE",

            status="INFO",

            payload={
                "message": (
                    "Duplicate transaction request "
                    "suppressed."
                ),

                "existing_order_id":
                    existing_tx.razorpay_order_id,

                "existing_status":
                    existing_tx.status,

                "idempotency_key":
                    existing_tx.idempotency_key
            },

            quote_id=existing_tx.quote_id
        )

        return TransactionResponse(

            status=(
                "REPLAY_SUPPRESSED_EXISTING_ORDER"
            ),

            decision="ALLOW",

            reason_code=(
                "IDEMPOTENT_CACHED_RESULT"
            ),

            razorpay_order_id=(
                existing_tx.razorpay_order_id
            ),

            amount_paise=(
                existing_tx.total_amount_paise
            ),

            negotiated_savings_paise=(
                savings_paise
            ),

            audit_trail={
                "idempotency_key":
                    existing_tx.idempotency_key,

                "quote_id":
                    existing_tx.quote_id,

                "is_replay": True,

                "original_transaction_status":
                    existing_tx.status
            }
        )


    # -----------------------------------------------------
    # STEP 5
    # MERCHANT QUOTE REQUEST
    #
    # Merchant performs deterministic negotiation and
    # reserves stock.
    # -----------------------------------------------------

    AuditService.log_event(
        db=db,

        mandate_id=mandate.mandate_id,

        event_type="QUOTE_REQUEST",

        actor="BUYER_AGENT",

        status="INFO",

        payload={
            "product_id": product_id,

            "requested_quantity":
                mandate.target_quantity,

            "offered_unit_price_paise":
                bid_unit_price_paise
        }
    )


    quote_data = merchant_agent.request_quote(

        db=db,

        mandate_id=mandate.mandate_id,

        product_id=product_id,

        requested_qty=(
            mandate.target_quantity
        ),

        offered_unit_price_paise=(
            bid_unit_price_paise
        )
    )


    # -----------------------------------------------------
    # STEP 6
    # MERCHANT REJECTION
    # -----------------------------------------------------

    if quote_data.get("status") == "REJECTED":

        reason = quote_data.get(
            "reason",
            "QUOTE_REJECTED"
        )

        AuditService.log_event(
            db=db,

            mandate_id=mandate.mandate_id,

            event_type="NEGOTIATION_FAILED",

            actor="MERCHANT_AGENT",

            status="FAILED",

            payload={
                "reason_code": reason,
                "product_id": product_id
            }
        )

        raise HTTPException(

            status_code=400,

            detail={
                "decision": "BLOCK",

                "reason_code": reason,

                "message": (
                    "Merchant rejected the quote "
                    "request. No payment action "
                    "was performed."
                )
            }
        )


    # -----------------------------------------------------
    # STEP 7
    # LOAD PERSISTED QUOTE
    # -----------------------------------------------------

    quote_id = quote_data["quote_id"]

    quote_record = (
        db.query(StockReservationQuote)
        .filter(
            StockReservationQuote.quote_id
            == quote_id
        )
        .first()
    )


    if not quote_record:

        AuditService.log_event(
            db=db,

            mandate_id=mandate.mandate_id,

            event_type="QUOTE_PERSISTENCE_FAILURE",

            actor="MERCHANT_AGENT",

            status="FAILED",

            payload={
                "quote_id": quote_id
            },

            quote_id=quote_id
        )

        raise HTTPException(

            status_code=500,

            detail={
                "decision": "BLOCK",

                "reason_code":
                    "QUOTE_NOT_PERSISTED",

                "message": (
                    "Quote could not be safely "
                    "loaded from persistent storage. "
                    "No payment was attempted."
                )
            }
        )


    # -----------------------------------------------------
    # STEP 8
    # EXPIRED QUOTE CHECK + INVENTORY RELEASE
    # -----------------------------------------------------

    if release_expired_quote_if_needed(
        db,
        quote_record
    ):

        AuditService.log_event(
            db=db,

            mandate_id=mandate.mandate_id,

            event_type="QUOTE_EXPIRED",

            actor="POLICY_ENGINE",

            status="BLOCKED",

            payload={
                "quote_id": quote_id,

                "message": (
                    "Quote expired before payment "
                    "authorization. Reserved stock "
                    "was released."
                )
            },

            quote_id=quote_id
        )

        raise HTTPException(

            status_code=400,

            detail={
                "decision": "BLOCK",

                "reason_code":
                    "QUOTE_EXPIRED",

                "message": (
                    "Quote expired and reserved "
                    "inventory was released. "
                    "No payment was attempted."
                )
            }
        )


    # -----------------------------------------------------
    # STEP 9
    # CANONICAL SHA-256 IDEMPOTENCY KEY
    # -----------------------------------------------------

    idempotency_key = (
        DeterministicPolicyEngine
        .generate_idempotency_key(

            mandate_id=mandate.mandate_id,

            merchant_id=(
                quote_record.merchant_id
            ),

            quote_id=quote_id,

            total_paise=(
                quote_record.total_amount_paise
            )
        )
    )


    # -----------------------------------------------------
    # STEP 10
    # DATABASE IDEMPOTENCY CHECK
    # -----------------------------------------------------

    existing_idempotent_tx = (
        AuditService
        .get_existing_transaction_by_idempotency(
            db,
            idempotency_key
        )
    )

    if existing_idempotent_tx:

        # Release current quote if this request somehow
        # created an additional reservation.

        MerchantSalesAgent.release_reservation(
            db,

            quote_id,

            reason="REPLAY_DUPLICATE"
        )

        AuditService.log_event(
            db=db,

            mandate_id=mandate.mandate_id,

            event_type="IDEMPOTENCY_HIT",

            actor="POLICY_ENGINE",

            status="INFO",

            payload={
                "message": (
                    "Canonical idempotency key "
                    "already exists."
                ),

                "idempotency_key":
                    idempotency_key,

                "existing_order_id":
                    existing_idempotent_tx
                    .razorpay_order_id
            },

            quote_id=quote_id
        )

        return TransactionResponse(

            status=(
                "REPLAY_SUPPRESSED_EXISTING_ORDER"
            ),

            decision="ALLOW",

            reason_code=(
                "IDEMPOTENT_CACHED_RESULT"
            ),

            razorpay_order_id=(
                existing_idempotent_tx
                .razorpay_order_id
            ),

            amount_paise=(
                existing_idempotent_tx
                .total_amount_paise
            ),

            negotiated_savings_paise=max(
                0,

                (
                    product_record
                    .retail_price_paise
                    * existing_idempotent_tx.quantity
                )

                -

                existing_idempotent_tx
                .total_amount_paise
            ),

            audit_trail={
                "idempotency_key":
                    idempotency_key,

                "is_replay": True
            }
        )


    # -----------------------------------------------------
    # STEP 11
    # DETERMINISTIC PAYMENT TRUST ENGINE
    #
    # This is the final policy authority.
    # -----------------------------------------------------

    decision, reason_code, message = (
        DeterministicPolicyEngine
        .validate_transaction(

            mandate=mandate,

            product=product_record,

            quote=quote_record
        )
    )


    # -----------------------------------------------------
    # STEP 12
    # POLICY BLOCK
    # -----------------------------------------------------

    if decision != "ALLOW":

        MerchantSalesAgent.release_reservation(

            db,

            quote_id,

            reason=reason_code
        )


        AuditService.log_event(

            db=db,

            mandate_id=mandate.mandate_id,

            event_type=(
                "GUARDRAIL_INTERCEPTION"
            ),

            actor="POLICY_ENGINE",

            status="BLOCKED",

            payload={

                "decision": decision,

                "reason_code":
                    reason_code,

                "message":
                    message,

                "attempted_total_paise":
                    quote_record
                    .total_amount_paise

            },

            quote_id=quote_id
        )


        # Store blocked attempt if possible.
        # The ledger remains useful for red-team
        # evidence and recovery auditing.

        try:

            AuditService.create_transaction_record(

                db=db,

                mandate_id=(
                    mandate.mandate_id
                ),

                idempotency_key=(
                    idempotency_key
                ),

                merchant_id=(
                    quote_record
                    .merchant_id
                ),

                product_id=product_id,

                quote_id=quote_id,

                quantity=(
                    quote_record.quantity
                ),

                unit_price_paise=(
                    quote_record
                    .unit_price_paise
                ),

                total_amount_paise=(
                    quote_record
                    .total_amount_paise
                ),

                status=(
                    f"GUARDRAIL_"
                    f"{reason_code}"
                )
            )

        except IntegrityError:

            db.rollback()


        raise HTTPException(

            status_code=400,

            detail={

                "decision":
                    decision,

                "reason_code":
                    reason_code,

                "message":
                    message
            }
        )


    # -----------------------------------------------------
    # STEP 13
    # POLICY ALLOW
    # -----------------------------------------------------

    AuditService.log_event(

        db=db,

        mandate_id=mandate.mandate_id,

        event_type="POLICY_VALIDATION",

        actor="POLICY_ENGINE",

        status="SUCCESS",

        payload={

            "decision":
                "ALLOW",

            "reason_code":
                reason_code,

            "checks_passed":[

                "MANDATE_EXPIRY",

                "MERCHANT_ALLOWLIST",

                "CATEGORY_SCOPE",

                "QUOTE_EXPIRY",

                "QUOTE_STATUS",

                "BUDGET_CAP",

                "QUANTITY_CAP",

                "SANITY_VALUES"

            ],

            "total_amount_paise":
                quote_record
                .total_amount_paise
        },

        quote_id=quote_id
    )


    # -----------------------------------------------------
    # STEP 14
    # CREATE PAYMENT ORDER
    #
    # Razorpay TEST MODE if credentials exist.
    #
    # MOCK/DEMO fallback if placeholder keys are used.
    # -----------------------------------------------------

    try:

        order = (
            payment_service
            .create_gated_order(

                amount_paise=(
                    quote_record
                    .total_amount_paise
                ),

                receipt_id=(
                    f"rcpt_"
                    f"{mandate.mandate_id[:10]}"
                ),

                notes={

                    "mandate_id":
                        mandate.mandate_id,

                    "quote_id":
                        quote_id,

                    "product_id":
                        product_id,

                    "buyer_id":
                        mandate.user_id

                },

                idempotency_key=(
                    idempotency_key
                )
            )
        )


    except Exception as payment_error:

        # -------------------------------------------------
        # PAYMENT FAILURE RECOVERY
        #
        # Important:
        # Release stock.
        # Do NOT consume inventory.
        # Do NOT mark payment/order as successful.
        # -------------------------------------------------

        MerchantSalesAgent.release_reservation(

            db,

            quote_id,

            reason="PAYMENT_ORDER_FAILED"
        )


        AuditService.log_event(

            db=db,

            mandate_id=mandate.mandate_id,

            event_type=(
                "PAYMENT_ORDER_FAILED"
            ),

            actor="RAZORPAY_GATEWAY",

            status="FAILED",

            payload={

                "quote_id":
                    quote_id,

                "error":
                    str(payment_error),

                "recovery":
                    "STOCK_RELEASED"

            },

            quote_id=quote_id
        )


        raise HTTPException(

            status_code=502,

            detail={

                "decision":
                    "BLOCK",

                "reason_code":
                    "PAYMENT_ORDER_CREATION_FAILED",

                "message": (
                    "Payment order creation failed. "
                    "Reserved stock was released. "
                    "No successful payment is claimed."
                )
            }
        )


    # -----------------------------------------------------
    # STEP 15
    # DETERMINE MODE
    # -----------------------------------------------------

    mock_mode = is_mock_order(order)


    if mock_mode:

        transaction_status = (
            "ORDER_CREATED_MOCK_MODE"
        )

        gateway_event = (
            "MOCK_ORDER_CREATED"
        )

        gateway_actor = (
            "MOCK_GATEWAY"
        )

    else:

        transaction_status = (
            "ORDER_CREATED_TEST_MODE"
        )

        gateway_event = (
            "RAZORPAY_TEST_ORDER_CREATED"
        )

        gateway_actor = (
            "RAZORPAY_GATEWAY"
        )


    # -----------------------------------------------------
    # STEP 16
    # CONSUME STOCK RESERVATION
    #
    # This happens after successful ORDER creation.
    #
    # IMPORTANT:
    # Creating an order is not the same as
    # payment settlement.
    # -----------------------------------------------------

    consumed = (
        MerchantSalesAgent
        .consume_reservation(

            db,

            quote_id
        )
    )


    if not consumed:

        AuditService.log_event(

            db=db,

            mandate_id=mandate.mandate_id,

            event_type=(
                "STOCK_CONSUMPTION_FAILURE"
            ),

            actor="POLICY_ENGINE",

            status="FAILED",

            payload={

                "quote_id":
                    quote_id,

                "order_id":
                    order.get("id"),

                "message": (
                    "Order was created but inventory "
                    "reservation could not be safely "
                    "consumed."
                )

            },

            quote_id=quote_id
        )


        raise HTTPException(

            status_code=500,

            detail={

                "decision":
                    "BLOCK",

                "reason_code":
                    "POST_ORDER_INVENTORY_FAILURE",

                "message": (
                    "Order was created but inventory "
                    "state requires recovery. "
                    "Check audit trail."
                )
            }
        )


    # -----------------------------------------------------
    # STEP 17
    # CREATE TRANSACTION LEDGER RECORD
    # -----------------------------------------------------

    try:

        transaction_record = (
            AuditService
            .create_transaction_record(

                db=db,

                mandate_id=(
                    mandate.mandate_id
                ),

                idempotency_key=(
                    idempotency_key
                ),

                merchant_id=(
                    quote_record
                    .merchant_id
                ),

                product_id=product_id,

                quote_id=quote_id,

                quantity=(
                    quote_record.quantity
                ),

                unit_price_paise=(
                    quote_record
                    .unit_price_paise
                ),

                total_amount_paise=(
                    quote_record
                    .total_amount_paise
                ),

                status=(
                    transaction_status
                ),

                razorpay_order_id=(
                    order.get("id")
                )
            )
        )


    except IntegrityError:

        # Database uniqueness is the final safety
        # boundary for duplicate idempotency keys.

        db.rollback()


        existing_transaction = (

            AuditService
            .get_existing_transaction_by_idempotency(

                db,

                idempotency_key
            )
        )


        if existing_transaction:

            return TransactionResponse(

                status=(
                    "REPLAY_SUPPRESSED_EXISTING_ORDER"
                ),

                decision="ALLOW",

                reason_code=(
                    "IDEMPOTENT_CACHED_RESULT"
                ),

                razorpay_order_id=(
                    existing_transaction
                    .razorpay_order_id
                ),

                amount_paise=(
                    existing_transaction
                    .total_amount_paise
                ),

                negotiated_savings_paise=max(

                    0,

                    (
                        product_record
                        .retail_price_paise
                        * existing_transaction.quantity
                    )

                    -

                    existing_transaction
                    .total_amount_paise
                ),

                audit_trail={

                    "idempotency_key":
                        idempotency_key,

                    "is_replay":
                        True
                }
            )


        raise


    # -----------------------------------------------------
    # STEP 18
    # FINAL PAYMENT / ORDER AUDIT EVENT
    # -----------------------------------------------------

    AuditService.log_event(

        db=db,

        mandate_id=mandate.mandate_id,

        event_type=gateway_event,

        actor=gateway_actor,

        status="SUCCESS",

        payload={

            "order_id":
                order.get("id"),

            "amount_paise":
                quote_record
                .total_amount_paise,

            "mode":

                (
                    "MOCK_DEMO"
                    if mock_mode
                    else "RAZORPAY_TEST_MODE"
                ),

            "important_note":

                (
                    "Order creation does not "
                    "represent confirmed payment "
                    "settlement."
                ),

            "idempotency_key":
                idempotency_key

        },

        quote_id=quote_id
    )


    # -----------------------------------------------------
    # STEP 19
    # CALCULATE SAVINGS
    # -----------------------------------------------------

    retail_total_paise = (

        product_record
        .retail_price_paise

        *

        quote_record.quantity
    )


    savings_paise = max(

        0,

        retail_total_paise

        -

        quote_record
        .total_amount_paise
    )


    # -----------------------------------------------------
    # STEP 20
    # SUCCESS RESPONSE
    # -----------------------------------------------------

    return TransactionResponse(

        status=transaction_status,

        decision="ALLOW",

        reason_code=(
            "PASSED_ALL_GUARDRAILS"
        ),

        razorpay_order_id=(
            order.get("id")
        ),

        amount_paise=(
            quote_record
            .total_amount_paise
        ),

        negotiated_savings_paise=(
            savings_paise
        ),
        cross_sell_offer=quote_data.get(
             "cross_sell_offer"
        ),

        audit_trail={

            "mandate_id":
                mandate.mandate_id,

            "quote_id":
                quote_id,

            "idempotency_key":
                idempotency_key,

            "payment_mode":

                (
                    "MOCK_DEMO"
                    if mock_mode
                    else "RAZORPAY_TEST_MODE"
                ),

            "payment_state":

                (
                    "ORDER_CREATED_NOT_SETTLED"
                ),

            "guardrail_status":
                "PASSED"
        }
    )


# ---------------------------------------------------------
# AUDIT LEDGER
# ---------------------------------------------------------

@app.get(
    "/api/v1/audit/{mandate_id}",
    response_model=AuditLedgerResponse
)
def get_audit_trail(

    mandate_id: str,

    db: Session = Depends(get_db)

):
    """
    Returns chronological audit telemetry
    for the specified mandate.
    """

    events = (

        db.query(AuditEventLog)

        .filter(
            AuditEventLog.mandate_id
            == mandate_id
        )

        .order_by(
            AuditEventLog.timestamp.asc()
        )

        .all()
    )


    transaction = (

        db.query(TransactionLedger)

        .filter(
            TransactionLedger.mandate_id
            == mandate_id
        )

        .order_by(
            TransactionLedger.created_at.desc()
        )

        .first()
    )


    timeline = []


    for event in events:

        try:

            details = json.loads(
                event.payload
            )

        except Exception:

            details = {
                "raw_payload":
                    event.payload
            }


        timeline.append({

            "timestamp":
                event.timestamp,

            "actor":
                event.actor,

            "event_type":
                event.event_type,

            "status":
                event.status,

            "details":
                details
        })


    return AuditLedgerResponse(

        mandate_id=mandate_id,

        transaction_status=(

            transaction.status

            if transaction

            else "NOT_FOUND"
        ),

        total_events=len(timeline),

        timeline=timeline
    )

# =============================================================
# RAZORPAY WEBHOOK - PAYMENT SETTLEMENT RECONCILIATION
# =============================================================

@app.post("/api/v1/webhooks/razorpay")
async def razorpay_webhook_handler(
    request: Request,
    x_razorpay_signature: Optional[str] = Header(None),
    db: Session = Depends(get_db)
):
    """
    Receives Razorpay webhook events and reconciles
    payment settlement with the local transaction ledger.
    """

    # ---------------------------------------------------------
    # 1. CHECK SIGNATURE HEADER
    # ---------------------------------------------------------

    if not x_razorpay_signature:
        raise HTTPException(
            status_code=400,
            detail="Missing Razorpay signature"
        )

    # ---------------------------------------------------------
    # 2. READ RAW REQUEST BODY
    # ---------------------------------------------------------

    raw_body = await request.body()

    # ---------------------------------------------------------
    # 3. VERIFY WEBHOOK SIGNATURE
    # ---------------------------------------------------------

    if not payment_service.verify_webhook_signature(
        raw_body,
        x_razorpay_signature
    ):
        raise HTTPException(
            status_code=400,
            detail="Invalid webhook signature"
        )

    # ---------------------------------------------------------
    # 4. PARSE VERIFIED WEBHOOK PAYLOAD
    # ---------------------------------------------------------

    payload = await request.json()
    event_type = payload.get("event")

    # ---------------------------------------------------------
    # 5. PROCESS SUCCESSFUL ORDER PAYMENT
    # ---------------------------------------------------------

    if event_type == "order.paid":

        try:

            order_entity = (
                payload
                .get("payload", {})
                .get("order", {})
                .get("entity", {})
            )

            razorpay_order_id = order_entity.get("id")

            if not razorpay_order_id:
                raise HTTPException(
                    status_code=400,
                    detail="Missing Razorpay order ID"
                )

            # -------------------------------------------------
            # FIND TRANSACTION IN LOCAL LEDGER
            # -------------------------------------------------

            tx = (
                db.query(TransactionLedger)
                .filter(
                    TransactionLedger.razorpay_order_id
                    == razorpay_order_id
                )
                .first()
            )

            # -------------------------------------------------
            # UPDATE TRANSACTION TO SETTLED
            # -------------------------------------------------

            if tx:

                # Prevent duplicate webhook processing
                if tx.status != "SETTLED":

                    tx.status = "SETTLED"

                    db.commit()

                    # -----------------------------------------
                    # AUDIT EVENT
                    # -----------------------------------------

                    AuditService.log_event(
                        db=db,
                        mandate_id=tx.mandate_id,
                        event_type="PAYMENT_SETTLED_WEBHOOK",
                        actor="RAZORPAY_GATEWAY",
                        status="SUCCESS",
                        payload={
                            "message": (
                                "Verified Razorpay webhook "
                                "signature and reconciled "
                                "transaction settlement"
                            ),
                            "razorpay_order_id": (
                                razorpay_order_id
                            )
                        },
                        quote_id=tx.quote_id
                    )

        except HTTPException:
            raise

        except Exception as error:

            db.rollback()

            raise HTTPException(
                status_code=500,
                detail=(
                    "Webhook processing failed: "
                    + str(error)
                )
            )

    # ---------------------------------------------------------
    # 6. ACKNOWLEDGE WEBHOOK
    # ---------------------------------------------------------

    return {
        "status": "ok",
        "event": event_type
    }